name: verma_app
description: "A customer/volunteer multi-platform app for Verma."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  openapi_generator_annotations: ^5.0.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  openapi_generator: ^5.0.2
  flutter_app_name: ^0.1.0

flutter:
  uses-material-design: true

flutter_app_name:
  name: "Verma"
